version: '3.7'
services:
  terraform:
    image: amazon/aws-cli:2.0.43
    working_dir: /work
    container_name: eks_terraform_container 
    volumes:
      - ./init.sh:/usr/local/bin/init.sh
      - ./terraform:/work
      - ../drone-ci/k8s:/work/k8s
    entrypoint: /bin/bash #override aws-cli entrypoint
    environment:
      - AWS_ACCESS_KEY_ID=${aws_access_key_id}
      - AWS_SECRET_ACCESS_KEY=${aws_secret_access_key}
      - AWS_DEFAULT_REGION=${aws_default_region}
    command: 
      -  init.sh
